version: '3'

services:
  app:
    build:
      context: .
      args:
        AMQP_ENABLED: ${AMQP_ENABLED}
        NODEJS_PACKAGE_MANAGER: ${NODEJS_PACKAGE_MANAGER}
    volumes:
      # Uncomment for speed optimization. See README.md
      # - var:/var/www/html/var
      # - vendor:/var/www/html/vendor
      # - node_modules:/var/www/html/node_modules
      - ./app:/var/www/html/
    ports: 
      - ${APACHE_SYSTEM_PORT}:80
    env_file:
      - .env

volumes:
  var:
  vendor:
  node_modules: