version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      args:
        AMQP_ENABLED: ${AMQP_ENABLED}
        NODEJS_PACKAGE_MANAGER: ${NODEJS_PACKAGE_MANAGER}
    volumes:
      # Uncomment for speed optimization. See README.md
      # - var:/var/www/html/var
      # - vendor:/var/www/html/vendor
      # - node_modules:/var/www/html/node_modules
      - ./app:/var/www/html/
    ports: 
      - ${APACHE_SYSTEM_PORT}:80
    env_file:
      - .env
    networks:
      - symfony
  db:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-13}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - ${POSTGRES_EXTERNAL_PORT:-15432}:5432
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  var:
  vendor:
  node_modules: