version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      args:
        APACHE_PORT: ${APACHE_PORT}
        AMQP_ENABLED: ${AMQP_ENABLED}
        NODEJS_PACKAGE_MANAGER: ${NODEJS_PACKAGE_MANAGER}
    volumes:
      # Uncomment 3 lines when symfony app is installed. See README.md
      # - var:/var/www/html/var
      # - vendor:/var/www/html/vendor
      # - node_modules:/var/www/html/node_modules
      - ./app:/var/www/html/
    ports: 
      - ${APACHE_EXT_PORT}:${APACHE_PORT}
    env_file:
      - .env
    networks:
      - symfony
  db:
    container_name: ${DB_HOST}
    image: postgres:${DB_VERS}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_EXT_PORT}:${DB_PORT}
    env_file:
      - .env
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  var:
  vendor:
  node_modules: